### ISSUE TITLE
balance checking error

### ISSUE THREAD

**Issue by yulonghe97** [QuilibriumNetwork/ceremonyclient#101]
When I checked the balance I got this error:

Input: `root@vmi1703183:~/ceremonyclient/node# GOEXPERIMENT=arenas /root/go/bin/node -balance`
Output: `-bash: /root/go/bin/node: No such file or directory`

**Comment by Freekers** [comment]
Not sure where you got that command from. Try running `GOEXPERIMENT=arenas go run ./... -balance` instead

**Comment by Freekers** [comment]
@CassOnMars No response from OP. Let's keep the issues clean and close this. Thanks
