### ISSUE TITLE
P2P issue

### ISSUE THREAD

**Issue by a3165458** [QuilibriumNetwork/ceremonyclient#110]
nvNjF695HatUvR1wktFdG5AEHic:\n  * [/ip4/94.72.117.94/udp/8336/quic] dial backoff"}
{"level":"info","ts":1709911553.7084908,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmP8C7g9ZRiWzhqN2AgFu5onS6HwHzR6Vv1TCHxAhnCSnq:\n  * [/ip4/65.108.194.84/udp/8336/quic] dial backoff"}
{"level":"info","ts":1709911553.7082407,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmYVaHXdFmHFeTa6oPixgjMVag6Ex7gLjE559ejJddwqzu:\n  * [/ip4/51.15.18.247/udp/8336/quic] dial backoff"}
{"level":"info","ts":1709911553.708798,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmPBYgDy7snHon7PAn8nv1shApQBQz1iHb2sBBS8QSgQwW:\n  * [/ip4/207.246.81.38/udp/8336/quic] dial backoff"}
{"level":"info","ts":1709911553.7089484,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmW6QDvKuYqJYYMP5tMZSp12X3nexywK28tZNgqtqNpEDL:\n  * [/ip4/186.233.184.181/udp/8336/quic] dial backoff"}
{"level":"info","ts":1709911553.7090929,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmeqBjm3iX7sdTieyto1gys5ruQrQNPKfaTGcVQQWJPYDV:\n  * [/ip4/204.186.74.46/udp/8316/quic] dial backoff"}
{"level":"info","ts":1709911553.7091136,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial Qmd233pLUDvcDW3ama27usfbG1HxKNh1V9dmWVW1SXp1pd:\n  * [/ip4/204.186.74.47/udp/8317/quic] dial backoff"}
{"level":"info","ts":1709911553.7095754,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial Qmekz5obb9qCRP5CrZ4D8Tmabbr5mJf6mgBJHTaitrx7Fx:\n  * [/ip4/185.209.178.115/udp/8336/quic] dial backoff"}
{"level":"info","ts":1709911553.7536309,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: no good addresses"}
{"level":"info","ts":1709911553.753755,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: no good addresses"}
{"level":"info","ts":1709911553.7538009,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: no good addresses"}
{"level":"info","ts":1709911553.7538571,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: no good addresses"}
{"level":"info","ts":1709911553.7575586,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: no good addresses"}
{"level":"info","ts":1709911553.7578814,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: no good addresses"}
{"level":"info","ts":1709911553.7580137,"caller":"p2p/blossomsub.go:336","msg":"error while connecting to dht peer","error":"failed to dial: no good addresses"}
{"level":"info","ts":1709911561.3822622,"caller":"master/master_clock_consensus_engine.go:174","msg":"peers in store","peer_store_count":18,"network_peer_count":0}
{"level":"info","ts":1709911571.3832698,"caller":"master/master_clock_consensus_engine.go:174","msg":"peers in store","peer_store_count":18,"network_peer_count":0}
![image](https://github.com/QuilibriumNetwork/ceremonyclient/assets/48400087/1388e37c-eef3-4325-9dba-578061189beb)

**Comment by CassOnMars** [comment]
if you're unable to reach any bootstrap peers your provider likely has blocked our bootstrap peers. please consider an alternative host
