### ISSUE TITLE
frame number sync too slow 

### ISSUE THREAD

**Issue by guotie** [QuilibriumNetwork/ceremonyclient#118]
I have run node for an hour, but the frame_number is 

{"level":"info","ts":1710235971.354947,"caller":"ceremony/ceremony_data_clock_consensus_engine.go:389","msg":"broadcasting peer info","frame_number":34}

**Comment by guotie** [comment]
{"level":"info","ts":1710236315.709698,"caller":"ceremony/consensus_frames.go:153","msg":"checking peer list","peers":1559,"uncooperative_peers":56,"current_head_frame":34}
{"level":"info","ts":1710236315.7097878,"caller":"ceremony/consensus_frames.go:187","msg":"polling peer for new frames","peer_id":"EiDqKv5t3cUAn+7hvG6c/wpIqMuPCe9lKyXN6IHd+j67Ow=="}
{"level":"info","ts":1710236315.709883,"caller":"ceremony/consensus_frames.go:153","msg":"checking peer list","peers":1558,"uncooperative_peers":57,"current_head_frame":34}
{"level":"info","ts":1710236315.7099679,"caller":"ceremony/consensus_frames.go:187","msg":"polling peer for new frames","peer_id":"EiCrcOHwgh4jyJx3qSlWZxJGZminoyFjgpYnPRO0wctijA=="}
{"level":"info","ts":1710236325.4247181,"caller":"master/master_clock_consensus_engine.go:176","msg":"peers in store","peer_store_count":514,"network_peer_count":103}
{"level":"info","ts":1710236334.042764,"caller":"ceremony/ceremony_data_clock_consensus_engine.go:309","msg":"preparing peer announce","frame_number":34}

**Comment by Freekers** [comment]
What are your node specs? Which provider are you using? More details are needed.

**Comment by shyba** [comment]
solved on 1.4.13 here

**Comment by shyba** [comment]
Yes, your node will spend the day talking to others and sometimes that fail.
The important part here is that it keeps trying, has enough peers to try and a high frame number.

**Comment by jJuXZJGd** [comment]
> Yes, your node will spend the day talking to others and sometimes that fail.
> 
> The important part here is that it keeps trying, has enough peers to try and a high frame number.

What confuses me is that it seems like every attempt at the beginning fails. So I even tried backing up the files and running a clean install, and this process will try for many days?

**Comment by shyba** [comment]
At the beginning it doesn't know a lot of good peers, so it will try bad ones and score them out until it reaches a state where most of them are healthy and the error is gone.
As long as you have enough "network_peer_count", you can safely ignore this.

**Comment by shyba** [comment]
latest version? if so, just wait a bit... it could take some hours

**Comment by anAngryAnt** [comment]
> latest version? if so, just wait a bit... it can take some hours

on the version: 1.4.16. I've been run for one day. the "frame_number" is still 0, "network_peer_count" is 38 and lots of"failed to dial: no good addresses" error.  is that normal?

<img width="1336" alt="image" src="https://github.com/QuilibriumNetwork/ceremonyclient/assets/11955967/fc964f31-f014-46f1-97bf-7fc2547d64ba">

**Comment by shyba** [comment]
The important part is "master frame synchronization needed to continue, waiting". From this you can view the progress.

`master_frame_head` needs to be above `max_data_frame_target` in order for it to continue

**Comment by huangsiyuan924** [comment]
> The important part is "master frame synchronization needed to continue, waiting". From this you can view the progress.
> 
> `master_frame_head` needs to be above `max_data_frame_target` in order for it to continue

Sir, can I copy the node/.config/store folder of other VPS to speed up synchronization?
