### ISSUE TITLE
what does this two key meaning in the log file?

### ISSUE THREAD

**Issue by MagicSen** [QuilibriumNetwork/ceremonyclient#120]
"my_balance":0
"lobby_state":"FINALIZING"

**Comment by Freekers** [comment]
If your balance is currently at zero, that is because the network is still in the pre-mainnet phase and rewards have not yet been distributed. Once Dusk (v1.5) launches, nodes that have participated should see a balance.

**Comment by MagicSen** [comment]
> If your balance is currently at zero, that is because the network is still in the pre-mainnet phase and rewards have not yet been distributed. Once Dusk (v1.5) launches, nodes that have participated should see a balance.

thanks
