### ISSUE TITLE
Node sync problem

### ISSUE THREAD

**Issue by Edson0908** [QuilibriumNetwork/ceremonyclient#121]
The node is running during 2 days. No QUIL accumulated. 
maxFrame Number always 34. 
When i started the node, i have err below :
`{"level":"info","ts":1710308599.9562888,"caller":"p2p/blossomsub.go:378","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmPBYgDy7snHon7PAn8nv1shApQBQz1iHb2sBBS8QSgQwW:\n  * [/ip4/207.246.81.38/udp/8336/quic] timeout: no recent network activity"}
{"level":"info","ts":1710308599.9562833,"caller":"p2p/blossomsub.go:378","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial Qmd233pLUDvcDW3ama27usfbG1HxKNh1V9dmWVW1SXp1pd:\n  * [/ip4/204.186.74.47/udp/8317/quic] timeout: no recent network activity"}
{"level":"info","ts":1710308599.956279,"caller":"p2p/blossomsub.go:378","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmZejZ8DBGQ6foX9recW73GA6TqL6hCMX9ETWWW1Fb8xtx:\n  * [/ip4/144.76.104.93/udp/8336/quic] timeout: no recent network activity"}
{"level":"info","ts":1710308599.9563026,"caller":"p2p/blossomsub.go:378","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmW6QDvKuYqJYYMP5tMZSp12X3nexywK28tZNgqtqNpEDL:\n  * [/ip4/186.233.184.181/udp/8336/quic] timeout: no recent network activity"}
{"level":"info","ts":1710308599.9564338,"caller":"p2p/blossomsub.go:378","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmYVaHXdFmHFeTa6oPixgjMVag6Ex7gLjE559ejJddwqzu:\n  * [/ip4/51.15.18.247/udp/8336/quic] timeout: no recent network activity"}
{"level":"info","ts":1710308600.3247917,"caller":"p2p/blossomsub.go:378","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmXbbmtS5D12rEc4HWiHWr6e83SCE4jeThPP4VJpAQPvXq:\n  * [/ip4/75.166.197.187/udp/8336/quic] timeout: no recent network activity"}
{"level":"info","ts":1710308600.3350616,"caller":"p2p/blossomsub.go:378","msg":"error while connecting to dht peer","error":"failed to dial: failed to dial QmS7C1UhN8nvzLJgFFf1uspMRrXjJqThHNN6AyEXp6oVUB:\n  * [/ip6/2001:41d0:8:823b::/udp/8336/quic] INTERNAL_ERROR (local): write udp6 [::]:44948->[2001:41d0:8:823b::]:8336: sendmsg: network is unreachable\n  * [/ip4/5.39.66.59/udp/8336/quic] timeout: no recent network activity"}`

after that there is no error. 
is the node running normally ?

**Comment by Freekers** [comment]
If your balance is currently at zero, that is because the network is still in the pre-mainnet phase and rewards have not yet been distributed. Once Dusk (v1.5) launches, nodes that have participated should see a balance.

Regarding the failed to dail / no recent network activity; which provider are you using? Looks like network traffic is being blocked.

**Comment by Edson0908** [comment]
> If your balance is currently at zero, that is because the network is still in the pre-mainnet phase and rewards have not yet been distributed. Once Dusk (v1.5) launches, nodes that have participated should see a balance.
> 
> Regarding the failed to dail / no recent network activity; which provider are you using? Looks like network traffic is being blocked.

We are using our own server instead of VPS

**Comment by Floryon** [comment]
Just to reopen. I have the same issue while using the recommended VDS 4 Server from Cherry Servers. Any recommendation which setting needs to be adjusted? 
For setting up the node I followed the quick-start guide, receival of keys also worked. Just no connection to peers possible. additionally the #91 seems to occur. Will post a screenshot a little later.
Thanks in advance!
