### ISSUE TITLE
High Memory Usage 

### ISSUE THREAD

**Issue by elprofessor-creator** [QuilibriumNetwork/ceremonyclient#126]
Hello @CassOnMars 

After 1.4.7 release memory usage is extremely increased. I have on 32G Ram servers and using %100 of memory. If swap is not enabled or not enough, OOM Killer makes restart the node.

Meanwhile, I realised that even machines with 64GB ram is also suffering...

Something wrong about memory usage at latest 2 version.

FYI,
Thanks

**Comment by tradersquareoff** [comment]
Same here. 32Go and 64Go servers are at 100% used mem all self owned bare metal.
Worst, frame are all stuck at 0.
Many reboot, clear, restart didn't make any change.
1.4.5 was working for most of my server but none since 1.4.7

**Comment by guotie** [comment]
yes, my memory has sharp surge to 85G, 1.4.6 and 1.4.7

**Comment by elprofessor-creator** [comment]
Seems like this problem is solved after 1.4.8

Memory usage is very acceptable.
