### ISSUE TITLE
how do i know node is running correctly?

### ISSUE THREAD

**Issue by yvvw** [QuilibriumNetwork/ceremonyclient#140]
hi, i have been running the node about two months ago by ```./poor_mans_cd.sh``` scripts. below is the running log. however, my balance is always zero. i have read the [FAQ](https://github.com/demipoet/demipoet.github.io?tab=readme-ov-file#whats-my-balance-why-am-i-still-at-0) and understand that the node needs to be synced. the size of ```.config/store``` is about 50G. how can i check if the node sync have finished? thank you.

```sh
$ GOEXPERIMENT=arenas go run . -balance
Owned balance: 0 QUIL
Unconfirmed balance: 0 QUIL
```

```sh
$ du -hs .config/*
16K     .config/config.yml
4.0K    .config/keys.yml
4.0K    .config/MIGRATIONS
4.0K    .config/RELEASE_VERSION
4.0K    .config/REPAIR
4.0K    .config/SELF_TEST
52G     .config/store
```

![image](https://github.com/QuilibriumNetwork/ceremonyclient/assets/15168529/a7d74f9b-10f2-49e7-b64a-ef714a882a4c)

**Comment by Freekers** [comment]
Balance will remain 0 until version 1.5 has launched.
