### ISSUE TITLE
arena

### ISSUE THREAD

**Issue by Lzggno1** [QuilibriumNetwork/ceremonyclient#145]
build source.quilibrium.com/quilibrium/monorepo/node: cannot load arena: malformed module path "arena": missing dot in first path element
I ran 'GOEXPERIMENT=arenas go run ./...', but it got an error. My go version is 1.13.8 linux/amd64

**Comment by Freekers** [comment]
Are you executing this command from the `node` folder?

**Comment by Lzggno1** [comment]
> Are you executing this command from the `node` folder?

Of course, I am operating under the node folder.

**Comment by Freekers** [comment]
> My go version is 1.13.8 linux/amd64

Your go version is too old. It has to be go1.20.x.
