### ISSUE TITLE
Error build qclient in v1.14.17

### ISSUE THREAD

**Issue by huangsiyuan924** [QuilibriumNetwork/ceremonyclient#172]
![image](https://github.com/QuilibriumNetwork/ceremonyclient/assets/47273722/29c57d3a-d99a-4631-ada8-2788551ce07f)

os: Ubuntu22.04
Quili version: 1.14.17
go version: 1.20.11

**Comment by agostbiro** [comment]
You need to enable arenas:

`GOEXPERIMENT=arenas go build -o qclient`

**Comment by huangsiyuan924** [comment]
> You need to enable arenas:
> 
> `GOEXPERIMENT=arenas go build -o qclient`

![image](https://github.com/QuilibriumNetwork/ceremonyclient/assets/47273722/dc3b1125-d846-47c3-9c91-c9e43c040653)
Sir, how to resolve this error?

**Comment by agostbiro** [comment]
You need to run the `GOEXPERIMENT=arenas go build -o qclient` command. I annotated the image:

![329845269-dc3b1125-d846-47c3-9c91-c9e43c040653](https://github.com/QuilibriumNetwork/ceremonyclient/assets/5764438/e29f81cd-8e92-4530-a2c9-a0b8c73ff49e)

**Comment by huangsiyuan924** [comment]
> You need to run the `GOEXPERIMENT=arenas go build -o qclient` command. I annotated the image:
> 
> ![329845269-dc3b1125-d846-47c3-9c91-c9e43c040653](https://private-user-images.githubusercontent.com/5764438/329846416-e29f81cd-8e92-4530-a2c9-a0b8c73ff49e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTU3NTMsIm5iZiI6MTcxNTUxNTQ1MywicGF0aCI6Ii81NzY0NDM4LzMyOTg0NjQxNi1lMjlmODFjZC04ZTkyLTQ1MzAtYTJjOS1hMGI4YzczZmY0OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTJUMTIwNDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWEyNjRhMjhiODhlMmU0MWEwNzcxNjk5MGEwZjJjOWM4OWU0ODQ3ZDRhZDUzMjhiMmM1MzNmNzQwYjdjODExZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nwFTG8nT6hwLWxkSu3SBYbpDYd9OV9DCSSsMU7OYL1w)

![image](https://github.com/QuilibriumNetwork/ceremonyclient/assets/47273722/32003205-7bbf-4c05-9f44-41fdbf1c9e0d)
yes, but got this error

**Comment by agostbiro** [comment]
> > You need to run the `GOEXPERIMENT=arenas go build -o qclient` command. I annotated the image:
> > ![329845269-dc3b1125-d846-47c3-9c91-c9e43c040653](https://private-user-images.githubusercontent.com/5764438/329846416-e29f81cd-8e92-4530-a2c9-a0b8c73ff49e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTU3NTMsIm5iZiI6MTcxNTUxNTQ1MywicGF0aCI6Ii81NzY0NDM4LzMyOTg0NjQxNi1lMjlmODFjZC04ZTkyLTQ1MzAtYTJjOS1hMGI4YzczZmY0OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTJUMTIwNDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWEyNjRhMjhiODhlMmU0MWEwNzcxNjk5MGEwZjJjOWM4OWU0ODQ3ZDRhZDUzMjhiMmM1MzNmNzQwYjdjODExZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nwFTG8nT6hwLWxkSu3SBYbpDYd9OV9DCSSsMU7OYL1w)
> 
> ![image](https://private-user-images.githubusercontent.com/47273722/329848343-32003205-7bbf-4c05-9f44-41fdbf1c9e0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTU5NzEsIm5iZiI6MTcxNTUxNTY3MSwicGF0aCI6Ii80NzI3MzcyMi8zMjk4NDgzNDMtMzIwMDMyMDUtN2JiZi00YzA1LTlmNDQtNDFmZGJmMWM5ZTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEyMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTkxNWM5MTU5MzkyZDM2ZDBlNmYxYTc5OGMzNGYzZjM5OTE3OWVkMDE1ZTY0NjZlMWY1MGEzZjAyNDc0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ab2idMFGcKMupiWY2kFu3FKXyrcFgzvz52qCuekIYEc) yes, but got this error

I'm not familiar with that one sorry. Are you sure that it's an error and not just a warning?

**Comment by huangsiyuan924** [comment]
> > > You need to run the `GOEXPERIMENT=arenas go build -o qclient` command. I annotated the image:
> > > ![329845269-dc3b1125-d846-47c3-9c91-c9e43c040653](https://private-user-images.githubusercontent.com/5764438/329846416-e29f81cd-8e92-4530-a2c9-a0b8c73ff49e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTU3NTMsIm5iZiI6MTcxNTUxNTQ1MywicGF0aCI6Ii81NzY0NDM4LzMyOTg0NjQxNi1lMjlmODFjZC04ZTkyLTQ1MzAtYTJjOS1hMGI4YzczZmY0OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTJUMTIwNDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWEyNjRhMjhiODhlMmU0MWEwNzcxNjk5MGEwZjJjOWM4OWU0ODQ3ZDRhZDUzMjhiMmM1MzNmNzQwYjdjODExZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nwFTG8nT6hwLWxkSu3SBYbpDYd9OV9DCSSsMU7OYL1w)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/47273722/329848343-32003205-7bbf-4c05-9f44-41fdbf1c9e0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTU5NzEsIm5iZiI6MTcxNTUxNTY3MSwicGF0aCI6Ii80NzI3MzcyMi8zMjk4NDgzNDMtMzIwMDMyMDUtN2JiZi00YzA1LTlmNDQtNDFmZGJmMWM5ZTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEyMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTkxNWM5MTU5MzkyZDM2ZDBlNmYxYTc5OGMzNGYzZjM5OTE3OWVkMDE1ZTY0NjZlMWY1MGEzZjAyNDc0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ab2idMFGcKMupiWY2kFu3FKXyrcFgzvz52qCuekIYEc) yes, but got this error
> 
> I'm not familiar with that one sorry. Are you sure that it's an error and not just a warning?

Ok thanks sir, now i had success build qclient!!!

**Comment by huangsiyuan924** [comment]
> > > > You need to run the `GOEXPERIMENT=arenas go build -o qclient` command. I annotated the image:
> > > > ![329845269-dc3b1125-d846-47c3-9c91-c9e43c040653](https://private-user-images.githubusercontent.com/5764438/329846416-e29f81cd-8e92-4530-a2c9-a0b8c73ff49e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTU3NTMsIm5iZiI6MTcxNTUxNTQ1MywicGF0aCI6Ii81NzY0NDM4LzMyOTg0NjQxNi1lMjlmODFjZC04ZTkyLTQ1MzAtYTJjOS1hMGI4YzczZmY0OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTJUMTIwNDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWEyNjRhMjhiODhlMmU0MWEwNzcxNjk5MGEwZjJjOWM4OWU0ODQ3ZDRhZDUzMjhiMmM1MzNmNzQwYjdjODExZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nwFTG8nT6hwLWxkSu3SBYbpDYd9OV9DCSSsMU7OYL1w)
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/47273722/329848343-32003205-7bbf-4c05-9f44-41fdbf1c9e0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTU5NzEsIm5iZiI6MTcxNTUxNTY3MSwicGF0aCI6Ii80NzI3MzcyMi8zMjk4NDgzNDMtMzIwMDMyMDUtN2JiZi00YzA1LTlmNDQtNDFmZGJmMWM5ZTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEyMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTkxNWM5MTU5MzkyZDM2ZDBlNmYxYTc5OGMzNGYzZjM5OTE3OWVkMDE1ZTY0NjZlMWY1MGEzZjAyNDc0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ab2idMFGcKMupiWY2kFu3FKXyrcFgzvz52qCuekIYEc) yes, but got this error
> > 
> > 
> > I'm not familiar with that one sorry. Are you sure that it's an error and not just a warning?
> 
> Ok thanks sir, now i had success build qclient!!!



> > > You need to run the `GOEXPERIMENT=arenas go build -o qclient` command. I annotated the image:
> > > ![329845269-dc3b1125-d846-47c3-9c91-c9e43c040653](https://private-user-images.githubusercontent.com/5764438/329846416-e29f81cd-8e92-4530-a2c9-a0b8c73ff49e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTU3NTMsIm5iZiI6MTcxNTUxNTQ1MywicGF0aCI6Ii81NzY0NDM4LzMyOTg0NjQxNi1lMjlmODFjZC04ZTkyLTQ1MzAtYTJjOS1hMGI4YzczZmY0OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTJUMTIwNDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWEyNjRhMjhiODhlMmU0MWEwNzcxNjk5MGEwZjJjOWM4OWU0ODQ3ZDRhZDUzMjhiMmM1MzNmNzQwYjdjODExZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nwFTG8nT6hwLWxkSu3SBYbpDYd9OV9DCSSsMU7OYL1w)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/47273722/329848343-32003205-7bbf-4c05-9f44-41fdbf1c9e0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTU5NzEsIm5iZiI6MTcxNTUxNTY3MSwicGF0aCI6Ii80NzI3MzcyMi8zMjk4NDgzNDMtMzIwMDMyMDUtN2JiZi00YzA1LTlmNDQtNDFmZGJmMWM5ZTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEyMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOTkxNWM5MTU5MzkyZDM2ZDBlNmYxYTc5OGMzNGYzZjM5OTE3OWVkMDE1ZTY0NjZlMWY1MGEzZjAyNDc0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ab2idMFGcKMupiWY2kFu3FKXyrcFgzvz52qCuekIYEc) yes, but got this error
> 
> I'm not familiar with that one sorry. Are you sure that it's an error and not just a warning?

Sir, can I copy the node/.config/store folder of other VPS to speed up synchronization?
