### ISSUE TITLE
Docker qclient cross-mint error

### ISSUE THREAD

**Issue by 0xOzgur** [QuilibriumNetwork/ceremonyclient#175]
Normally docker node commands has structure like below

```
docker compose exec node qclient help
docker compose exec node qclient token help
docker compose exec node qclient token balance
```

When using crossmint function with this structure, throws error
```
`docker compose exec node qclient cross-mint 0x0000000`
config directory doesn't exist: ../node/.config/
```

We need to run command with config flag.
`docker compose exec node qclient cross-mint --config .config 0x0000000`

@agostbiro @mscurtescu

**Comment by agostbiro** [comment]
Thanks for the detailed report @0xOzgur ! I'm not familiar with the Docker setup, so I'd defer to @mscurtescu

**Comment by mscurtescu** [comment]
Up until 1.4.17 the `qclient` command was just a dummy placeholder, no real config was loaded, the `cross-min` subcommand is the first that is also loading the config.

The config folder is hard coded to load from a relative folder for `qclient`, and that will not work as expected if the binary is installed and run from PATH:
https://github.com/QuilibriumNetwork/ceremonyclient/blob/main/client/cmd/root.go#L28

Working on a PR that fixes this...

**Comment by mscurtescu** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/176

**Comment by 0xOzgur** [comment]
@mscurtescu Great job, thank you!
