### ISSUE TITLE
how to config grpc

### ISSUE THREAD

**Issue by lll7xi** [QuilibriumNetwork/ceremonyclient#180]
when i want to check balance, and run command **GOEXPERIMENT=arenas go run ./... -balance**

error like this:
gRPC Not Enabled, Please Configure
exit status 1

but i realy have config the grpc

**Comment by 0xOzgur** [comment]
Please read the manual https://docs.quilibrium.space/installation/configurations

**Comment by 0xOzgur** [comment]
@lll7xi Did you solve your issue? If yes, you can close this issue :)

**Comment by morismc09** [comment]
Same happened for me. Even after the configuration. Is it because of the update to version 2.0?
