### ISSUE TITLE
The keys.yml is null

### ISSUE THREAD

**Issue by xuht724** [QuilibriumNetwork/ceremonyclient#185]
When I run the guidance as below:
```
cd ~/ceremonyclient/node
GOEXPERIMENT=arenas go run ./...
```
The output is 
```
Creating config directory .config
Generating default config...
Generating random host key...
Generating keystore key...
Saving config...
Clearing test data...
Loading ceremony state and starting node...
{"level":"info","ts":171620352
```

But the data in keys.yml is :
```
null
```

The bug has been issued by [issue-100](https://github.com/QuilibriumNetwork/ceremonyclient/issues/100), however, it seems that there is no available method to solve.

**Comment by 0xOzgur** [comment]
If your key is `null:` just let it your node run for a while. It will generade keys.yml itself. At first run of node it is created with `null:` then generates keys.

**Comment by agostbiro** [comment]
If you encounter this issue after 1.4.18, please see: https://github.com/QuilibriumNetwork/ceremonyclient/issues/209
