### ISSUE TITLE
Error 137

### ISSUE THREAD

**Issue by gregegan** [QuilibriumNetwork/ceremonyclient#2]
Hi @CassOnMars -

I'm attempting to run the sequencer in Docker, although looks like i'm getting a Error 137. Any ideas?

<img width="448" alt="image" src="https://user-images.githubusercontent.com/6665100/232945897-b77d9854-5e19-465d-ba4e-73b494ca025e.png">

Greg

**Comment by CassOnMars** [comment]
error 137 is usually an OOM error, you might need to adjust your allocation for Docker

**Comment by gregegan** [comment]
Looks like using node `nvm use 16.15.1` worked just fine

**Comment by CassOnMars** [comment]
that's... very strange – not sure why node version would impact your docker memory state, unless it somehow impacted your other docker containers

**Comment by laurensV** [comment]
Is there a Dockerfile/docker image available to run this in docker?

**Comment by CassOnMars** [comment]
Not officially, although some have written their own. We're going to add one, but the task for that is on our backlog.
