### ISSUE TITLE
mac m2 chips not supported

### ISSUE THREAD

**Issue by wenpengwu** [QuilibriumNetwork/ceremonyclient#200]
When I run
 GOEXPERIMENT=arenas go run . /...

the terminal shows
Digest file not found
exit status 1

My version of go is

$ go version
go version go1.20.14 darwin/arm64

**Comment by wenpengwu** [comment]
checkout v1.4.17 run success .but v1.4.18  will show the error

**Comment by mcloebel** [comment]
Same issue here on i7 with v1.4.18.

go version go1.20.14 linux/amd64

**Comment by mcloebel** [comment]
using release_autorun.sh for startup will fix the issue

**Comment by wenpengwu** [comment]
refer #204
