### ISSUE TITLE
Digest file not found

### ISSUE THREAD

**Issue by Cyncra** [QuilibriumNetwork/ceremonyclient#201]
When trying to run the 1.4.18 version that was pushed 30 minutes ago, I get the message "Digest file not found" and it exits with status 1.

**Comment by 3Fulieak** [comment]
I also encountered the same problem

**Comment by CarterAppleton** [comment]
same thing here

```
quilibrium/node on  main [?] via 🐹 v1.20.14
❯ GOEXPERIMENT=arenas go run ./...
Digest file not found
exit status 1
```

Ubuntu 22.04.4

**Comment by Cyncra** [comment]
cd ceremonyclient && git pull
git checkout release
cd node && ./release_autorun.sh

**Comment by Cyncra** [comment]
cd ceremonyclient && git pull
git checkout release
cd node && ./release_autorun.sh
