### ISSUE TITLE
The files 'ceremony.json' and 'retroactive_peers.json' are indeed missing

### ISSUE THREAD

**Issue by ZhengHui-Z** [QuilibriumNetwork/ceremonyclient#202]
The Dockerfile cannot be executed successfully due to missing files. I have thoroughly checked the relevant records and found that the files 'ceremony.json' and 'retroactive_peers.json' are indeed missing.

```
COPY --from=build /opt/ceremonyclient/node/ceremony.json /root
COPY --from=build /opt/ceremonyclient/node/retroactive_peers.json /root
```

```shell
docker build --build-arg GIT_COMMIT=$(git log -1 --format=%h) -t quilibrium -t quilibrium:1.4.18 .
```

**Comment by ephz3nt** [comment]
check:
https://github.com/QuilibriumNetwork/ceremonyclient/pull/199/files

**Comment by fuckrunes** [comment]
![image](https://github.com/QuilibriumNetwork/ceremonyclient/assets/166901538/eeb0957c-9ec0-49dc-8904-61d5e0695813)

**Comment by lll7xi** [comment]
need fix
