### ISSUE TITLE
Release branch bug, release_autorun. sh Error in determining CPU platform

### ISSUE THREAD

**Issue by shaonianpro** [QuilibriumNetwork/ceremonyclient#203]
Fix arm execution [release-autorun.sh](https://github.com/QuilibriumNetwork/ceremonyclient/blob/cfe77453c685738cf40b559af920ec7265b941da/node/release_autorun.sh#L6) unable to start

- before：

`if [[ $arch == arm* ]]; then`

- after:

`if [[ arch == arm* ]]; then`

- run script
`sed -i 's|$arch|arch|' release_autorun.sh `

**Comment by agostbiro** [comment]
Hi, thanks for reporting this issue! Could you elaborate please on the problem that you're facing? Are you unable to start a node with the `release_autorun.sh` script on ARM Linux?
