### ISSUE TITLE
How can I determine if my version 1.4.18 is working properly?

### ISSUE THREAD

**Issue by tigger404** [QuilibriumNetwork/ceremonyclient#208]
<img width="1372" alt="image" src="https://github.com/QuilibriumNetwork/ceremonyclient/assets/18521569/fa49fcc8-0c05-4d85-9778-13a0d3dcffe4">
Is it normal if the message in the log always says "peers in store" or "connecting to bootstrap" or "setting syncing target"?
Just like the picture I mentioned above.
Verison:1.4.18
Plz help me ,thx~!

**Comment by tigger404** [comment]
<img width="1444" alt="image" src="https://github.com/QuilibriumNetwork/ceremonyclient/assets/18521569/cb3b6162-71a9-4730-b037-492704e397fb">
I noticed a new log entry: "msg":"broadcasting self-test info","current_frame":941635. So, the appearance of current_frame indicates that my current version 1.4.18 is functioning properly, right?

**Comment by agostbiro** [comment]
Hi, the output looks normal to me 👍

**Comment by redbaron-gt** [comment]
New node started from v1.4.18. Get lot of warnings.
<img width="1308" alt="Screenshot 2024-05-26 at 14 26 40" src="https://github.com/QuilibriumNetwork/ceremonyclient/assets/10510599/4b41fe92-2a9c-44f9-a9f0-62a1d887ff1f">
Is it normal?

**Comment by nmateo** [comment]
> New node started from v1.4.18. Get lot of warnings. <img alt="Screenshot 2024-05-26 at 14 26 40" width="1308" src="https://private-user-images.githubusercontent.com/10510599/333871829-4b41fe92-2a9c-44f9-a9f0-62a1d887ff1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MjAwODQsIm5iZiI6MTcxNjcxOTc4NCwicGF0aCI6Ii8xMDUxMDU5OS8zMzM4NzE4MjktNGI0MWZlOTItMmE5Yy00NGY5LWE5ZjAtNjJhMWQ4ODdmZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEwMzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNTdlNWM3ZGY0YWE2YTY5MzA0MzBlZWM0ZDRhMGZjODM2ZDQ5MTc2OWExYzA1OWFmMGFiNjI4YTc5Nzc4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aIRorFpvkPEo4bXsFinYiDklkh0i37J0ZKD57FIf92E"> Is it normal?

+1, I got the same

**Comment by agostbiro** [comment]
Yep it's normal. "received invalid proof" means someone's spamming your node.
