### ISSUE TITLE
Stucked Keys.yml generation.

### ISSUE THREAD

**Issue by 0xOzgur** [QuilibriumNetwork/ceremonyclient#209]
When running new node, machine doesn't generate content of keys.yml.

Keys.yml file is null: but doesnt create keypairs.

Based on feedbacks of community, I also personally tested with ./release_autorun.sh file and directly binary and can confirm this.

Test is done at amd64 architecture.

**Comment by redbaron-gt** [comment]
Same here!

**Comment by agostbiro** [comment]
Thanks for reporting this! 

The key file being empty for newly created nodes after the 1.4.18 release is not a problem as the rewards accrue to the peer key now which is in the config file. For context, previously the key for the ceremony application was stored in the `keys.yml` file, but the ceremony application was disabled with the 1.4.18 release, hence the empty `keys.yml` file.

The content being null is a bug which will be fixed, but it's not causing anybody to lose rewards.

Going forwards, it's best to continue backing up both the `config.yml` and `keys.yml` files in case a future update adds new keys to `keys.yml`.

**Comment by redbaron-gt** [comment]
> Going forwards, it's best to continue backing up both the `config.yml` and `keys.yml` files in case a future update adds new keys to `keys.yml`.

Thank you for explanation. Mostly I need the key.yml backup to restore same server anywhere if current is deleted. If restore is possible with key.yml empty, it's OK for me!

**Comment by nmateo** [comment]
> Thanks for reporting this!
> 
> The key file being empty for newly created nodes after the 1.4.18 release is not a problem as the rewards accrue to the peer key now which is in the config file. For context, previously the key for the ceremony application was stored in the `keys.yml` file, but the ceremony application was disabled with the 1.4.18 release, hence the empty `keys.yml` file.
> 
> The content being null is a bug which will be fixed, but it's not causing anybody to lose rewards.
> 
> Going forwards, it's best to continue backing up both the `config.yml` and `keys.yml` files in case a future update adds new keys to `keys.yml`.

So being a new node i can just backup the config.yml and it's essetnially my wallet ? as the keys.yml is just "null:"

**Comment by agostbiro** [comment]
@nmateo yes, but if you have an automated backup method, it's best to keep backing up both `config.yml` and `keys.yml` in case a future update adds keys to `keys.yml` again.

**Comment by nmateo** [comment]
> @nmateo yes, but if you have an automated backup method, it's best to keep backing up both `config.yml` and `keys.yml` in case a future update adds keys to `keys.yml` again.

But then again, where are our keys then ? when i run   grpcurl -plaintext GetTokenInfo method, it return ERROR: Message: get token info: key not found.

**Comment by agostbiro** [comment]
`GetTokenInfo` was specific to the ceremony application so it broke as well after its removal in 1.4.18: https://github.com/QuilibriumNetwork/ceremonyclient/issues/210

Token rewards will be posted to the website: https://quilibrium.com/rewards/

**Comment by agostbiro** [comment]
The only key relevant now is the `peerPrivKey` in `config.yml`.

**Comment by 0xOzgur** [comment]
Closed regarding to detailed info @agostbiro shared with us.

I will be sharing link of this issue if any question from community.

**Comment by 0xOzgur** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/216/commits/b9ea4c158e4657c09976fa6b2e625b3809119687
