### ISSUE TITLE
 doesn't exist: .config/

### ISSUE THREAD

**Issue by xxxJay123** [QuilibriumNetwork/ceremonyclient#242]
![image](https://github.com/QuilibriumNetwork/ceremonyclient/assets/139091091/c011eec8-851c-4042-8a1b-9e68d14b78ec)
I cannot do while I update to 1.6.17

**Comment by 0xLennyy** [comment]
cd ~/ceremonyclient/client
./qclient --config=../node/.config/ cross-mint 0x000000000000000000000000000000

--config=<.config  path>

**Comment by xxxJay123** [comment]
![image](https://github.com/QuilibriumNetwork/ceremonyclient/assets/139091091/eab3992f-1358-42d4-a98e-e0d1323dd053)
![image](https://github.com/QuilibriumNetwork/ceremonyclient/assets/139091091/9a5a9e33-af81-4aca-846f-a94c37b40468)

is work, but 'An invalid cross mint proof was provided'....

**Comment by 0xOzgur** [comment]
Means you provided it for the wrong peer id, make sure you are choosing correct peer id of your node and you havent claimed before.
