### ISSUE TITLE
feature request: log worker connection refusals in core 0 rather than panic

### ISSUE THREAD

**Issue by grenade** [QuilibriumNetwork/ceremonyclient#243]
when the core 0 thread receives a response of `connection refused` or `no route to host` from a data worker configured in `config.yml` `.engine.dataWorkerMultiaddrs`, it responds by issuing a panic and the core 0 thread then crashes.

it would be a nice feature if missing network worker threads were not able to cause the core 0 thread to crash but instead just log the absence of the worker.

**Comment by CassOnMars** [comment]
v1.4.20 now handles this a lot more gracefully 🫡
