### ISSUE TITLE
got error in go run

### ISSUE THREAD

**Issue by K-tang-mkv** [QuilibriumNetwork/ceremonyclient#254]
When I run 
```
CGO_LDFLAGS="-L/root/ceremonyclient/target/release -lvdf -ldl -lm"     CGO_ENABLED=1     GOEXPERIMENT=arenas     go run ./... --signature-check=false
```
But failed with these error:
```
# source.quilibrium.com/quilibrium/monorepo/node
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_ffi_bls48581_rustbuffer_from_bytes':
/tmp/go-build/cgo-gcc-prolog:68: undefined reference to `ffi_bls48581_rustbuffer_from_bytes'
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_ffi_bls48581_uniffi_contract_version':
/tmp/go-build/cgo-gcc-prolog:87: undefined reference to `ffi_bls48581_uniffi_contract_version'
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_checksum_func_commit_raw':
/tmp/go-build/cgo-gcc-prolog:106: undefined reference to `uniffi_bls48581_checksum_func_commit_raw'
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_checksum_func_init':
/tmp/go-build/cgo-gcc-prolog:125: undefined reference to `uniffi_bls48581_checksum_func_init'
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_checksum_func_prove_raw':
/tmp/go-build/cgo-gcc-prolog:144: undefined reference to `uniffi_bls48581_checksum_func_prove_raw'
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_checksum_func_verify_raw':
/tmp/go-build/cgo-gcc-prolog:163: undefined reference to `uniffi_bls48581_checksum_func_verify_raw'
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_fn_func_commit_raw':
/tmp/go-build/cgo-gcc-prolog:183: undefined reference to `uniffi_bls48581_fn_func_commit_raw'
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_fn_func_prove_raw':
/tmp/go-build/cgo-gcc-prolog:216: undefined reference to `uniffi_bls48581_fn_func_prove_raw'
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_fn_func_verify_raw':
/tmp/go-build/cgo-gcc-prolog:240: undefined reference to `uniffi_bls48581_fn_func_verify_raw'
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_ffi_bls48581_rustbuffer_free':
/tmp/go-build/cgo-gcc-prolog:52: undefined reference to `ffi_bls48581_rustbuffer_free'
/usr/bin/ld: /tmp/go-link-3463163796/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_fn_func_init':
/tmp/go-build/cgo-gcc-prolog:198: undefined reference to `uniffi_bls48581_fn_func_init'
collect2: error: ld returned 1 exit status
```

**Comment by K-tang-mkv** [comment]
I'm in Ubuntu 22.04 os with gcc, rust, and go.

**Comment by creativebluecat** [comment]
# source.quilibrium.com/quilibrium/monorepo/node
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_ffi_bls48581_rustbuffer_from_bytes':
/tmp/go-build/cgo-gcc-prolog:68: undefined reference to `ffi_bls48581_rustbuffer_from_bytes'
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_ffi_bls48581_uniffi_contract_version':
/tmp/go-build/cgo-gcc-prolog:87: undefined reference to `ffi_bls48581_uniffi_contract_version'
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_checksum_func_commit_raw':
/tmp/go-build/cgo-gcc-prolog:106: undefined reference to `uniffi_bls48581_checksum_func_commit_raw'
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_checksum_func_init':
/tmp/go-build/cgo-gcc-prolog:125: undefined reference to `uniffi_bls48581_checksum_func_init'
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_checksum_func_prove_raw':
/tmp/go-build/cgo-gcc-prolog:144: undefined reference to `uniffi_bls48581_checksum_func_prove_raw'
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_checksum_func_verify_raw':
/tmp/go-build/cgo-gcc-prolog:163: undefined reference to `uniffi_bls48581_checksum_func_verify_raw'
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_fn_func_commit_raw':
/tmp/go-build/cgo-gcc-prolog:183: undefined reference to `uniffi_bls48581_fn_func_commit_raw'
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_fn_func_prove_raw':
/tmp/go-build/cgo-gcc-prolog:216: undefined reference to `uniffi_bls48581_fn_func_prove_raw'
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_fn_func_verify_raw':
/tmp/go-build/cgo-gcc-prolog:240: undefined reference to `uniffi_bls48581_fn_func_verify_raw'
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_ffi_bls48581_rustbuffer_free':
/tmp/go-build/cgo-gcc-prolog:52: undefined reference to `ffi_bls48581_rustbuffer_free'
/usr/bin/ld: /tmp/go-link-1637099852/000007.o: in function `_cgo_989782a52565_Cfunc_uniffi_bls48581_fn_func_init':
/tmp/go-build/cgo-gcc-prolog:198: undefined reference to `uniffi_bls48581_fn_func_init'
collect2: error: ld returned 1 exit status

i got the same error , is any method to solve it ?

**Comment by PalanQu** [comment]
@K-tang-mkv @creativebluecat 

Run `generate.sh` in bls48581, and run following script, add bls48581 link for `CGO_LDFLAGS`

```
CGO_LDFLAGS="-L/path/to/ceremonyclient/target/release -lvdf -lbls48581 -ldl -lm" \
        CGO_ENABLED=1 \
        GOEXPERIMENT=arenas \
        go run ./... --signature-check=false
```
