### ISSUE TITLE
Can you please help clarify some questions? (No discussion board so hope it is ok I raise them here)

### ISSUE THREAD

**Issue by johnnynanjiang** [QuilibriumNetwork/ceremonyclient#28]
1. Is the network Byzantine fault tolerance?

2. Is there a spec for node hardware? Does it require a HSM for DKG?

3. Is the project open source? As I just saw one repo "ceremonyclient"

4. Are their any Telegram / Discord chat group for the community?

Thanks and regards,
Johnny

**Comment by CassOnMars** [comment]
1. BFT is probabilistic through a deterministic fork choice rule and a cryptographically secure pseudorandom number generation beacon for setting leader election (with subleaders for a given frame if the leader is offline).
2. Hardware spec is given in the readme, will reduce to Raspberry Pi 4 as minimum in the Dusk phase of the network launch.
3. This is a mirror of the full repo, which will go live with Dusk (and continue to be mirrored on github)
4. We have a telegram for node operators, you can find it on our Farcaster channel http://warpcast.com/~/channel/quilibrium

**Comment by johnnynanjiang** [comment]
`This is a mirror of the full repo, which will go live with Dusk (and continue to be mirrored on github)`

If I understand correctly, it would be open source in a way that some parts would be masked?
