### ISSUE TITLE
gRPC Not Enabled, Please Configure

### ISSUE THREAD

**Issue by morismc09** [QuilibriumNetwork/ceremonyclient#288]
I followed the configuration here https://docs.quilibrium.space/configurations after installing my node which seems to be running fine.

Also the file config.yml has been changed according to the documentation. I cross-checked everything many times, but when I use the command

`cd ~/ceremonyclient/node && ./node-1.4.21.1-linux-amd64 -balance`

I receive the following output:

```
Signature check passed
gRPC Not Enabled, Please Configure
```

I even restarted the service with `service ceremonyclient restart` but no change. 

I also found out that there is no server listening on port 8337 which should be the case. Do I have to start the gRPC server separately and if yes, where is it documented?

**Comment by tjsturos** [comment]
First, if you've already determined the server is not listening it means you do not have the config set up correctly.

The server will automatically start listening if the config is set for it.

Second, you need to make sure that the ceremonyclient/node/.config/config.yml file has this:
```yaml
...
  difficulty: 0
db:
  path: .config/store
listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337
listenRESTMultiaddr: "" (or /ip4/127.0.0.1/tcp/8335)
logFile: ""
```

Make sure the listenGrpcMultiaddr is at the root/bottom of the config file (no spaces in front).

If you had to make any changes, then restart the application. Try again after a few minutes (you should see at least one "peers in store" log before trying.

If it still doesn't work, make sure you have grpcurl installed.  

Typically this is done via a go install (install go to make the following work): 

```bash
go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
```

Then try again.
