### ISSUE TITLE
Can't build docker image because go.sum is out of date

### ISSUE THREAD

**Issue by danimbrogno** [QuilibriumNetwork/ceremonyclient#294]
I got stuck for a bit trying to rebuild the source docker image using the task file. 

When I ran `task build:source`

The command `go build -o qclient ./main.go` failed.

After some digging I fixed it by editing the Dockerfile.source to add:

`RUN go mod tidy`
before
`RUN go build -o qclient ./main.go`

Not a go dev, but I think this means go.sum might be out of date?

**Comment by CassOnMars** [comment]
should be fixed now
