### ISSUE TITLE
setup config files for mainnet vs testnet

### ISSUE THREAD

**Issue by nguyenhuumy** [QuilibriumNetwork/ceremonyclient#339]
Many params in this project are hardcoded like this one https://github.com/QuilibriumNetwork/ceremonyclient/commit/5f9ea8262f411bd9316b853a43935218a6e11ef8
As this project grows, it is very different to maintain. Please set up configuration files.

**Comment by CassOnMars** [comment]
testnet iterations are frequently shifting with many resetting genesis events, and configuration files are frequently stale. as things reach a point of stability where testnet versions are long lived, this makes sense, but at the current iteration, it doesn't yet
