### ISSUE TITLE
wallet balance from node command.

### ISSUE THREAD

**Issue by ravinayag** [QuilibriumNetwork/ceremonyclient#37]
Request Type : Feature/Enahancement.

Currently the `node` binary has the below options, however having `-get-balance`   feature will help to get the balance details vs 
 `-db-console` and looking at the right bottom  screen for balances. 
 This option should able to give straight forward response for operators query to get current wallet balance.

```
~/ceremonyclient/node$ ./node --help
Usage of ./node:
  -config string
        the configuration directory (default ".config")
  -db-console
        starts the node in database console mode
  -import-priv-key string
        creates a new config using a specific key from the phase one ceremony
  -peer-id
        print the peer id to stdout from the config and exit
```

**Comment by agostbiro** [comment]
@CassOnMars would you accept a PR implementing this feature?

**Comment by CassOnMars** [comment]
> @CassOnMars would you accept a PR implementing this feature?

Absolutely!
