### ISSUE TITLE
Issue: Balance flag returns "item not found" error

### ISSUE THREAD

**Issue by tekinsercan** [QuilibriumNetwork/ceremonyclient#54]
I'm reaching out to request your assistance with an issue I've encountered while querying the balance on our node, which is running in a Docker container.

Despite confirming successful network connectivity with the following output:
```
/opt/ceremonyclient/node # nc -zv 0.0.0.0 8337
0.0.0.0 (0.0.0.0:8337) open
/opt/ceremonyclient/node #
```
Additionally, using the `--db-console` option indicates a `CONNECTED` status:
```
STATUS  CONNECTED
```
I'm facing an issue when attempting to execute the balance command:
```
/opt/ceremonyclient/node # go run ./... -balance
panic: error getting token info: rpc error: code = Unknown desc = get token info: get highest candidate data clock frame: item not found

goroutine 1 [running]:
main.main()
	/opt/ceremonyclient/node/main.go:101 +0x745
exit status 2
/opt/ceremonyclient/node #
```
Could you please advise if there's a specific configuration or step I might be missing?
Thank you!

**Comment by sercanCyberVision** [comment]
Executed the command again, and it works now, I did not change anything:
```
/opt/ceremonyclient/node # go run ./... -balance
Confirmed balance: 0 QUIL
/opt/ceremonyclient/node #
```
FYI

**Comment by tekinsercan** [comment]
Executed the command again, and it works now, I did not change anything:
```
/opt/ceremonyclient/node # go run ./... -balance
Confirmed balance: 0 QUIL
/opt/ceremonyclient/node #
```
FYI

**Comment by CassOnMars** [comment]
it just needed to sync, all good!

**Comment by sercanCyberVision** [comment]
Thank you @CassOnMars!

Does updating the balance amount require some time to sync too? After two full days, it has not change
