### ISSUE TITLE
Issue: Balance flags connection refused error 

### ISSUE THREAD

**Issue by JustinCheng0509** [QuilibriumNetwork/ceremonyclient#65]
`panic: error getting token info: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 0.0.0.0:8337: connect: connection refused"

goroutine 1 [running]:
main.main()
	/home/ubuntu/ceremonyclient/node/main.go:101 +0x745
exit status 2`

Was receiving this error when editing my multiaddr, tried with 127.0.0.1 did not work as well. 

I ran a netstat and checked the 8337 port was not occupied. 
`sudo netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      507/systemd-resolve 
tcp        0      0 127.0.0.54:53           0.0.0.0:*               LISTEN      507/systemd-resolve 
tcp6       0      0 :::22                   :::*                    LISTEN      1/init              
`

Working off a VPS (OVHCloud to be exact). Everything else seems to be working. and VPS firewall was disabled on OVH side. 
Seeking out to get some help! Thanks,

**Comment by JustinCheng0509** [comment]
`sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere                  
8336                       ALLOW       Anywhere                  
8337                       ALLOW       Anywhere                  
8338                       ALLOW       Anywhere                  
8317                       ALLOW       Anywhere                  
8316                       ALLOW       Anywhere                  
22 (v6)                    ALLOW       Anywhere (v6)             
8336 (v6)                  ALLOW       Anywhere (v6)             
8337 (v6)                  ALLOW       Anywhere (v6)             
8338 (v6)                  ALLOW       Anywhere (v6)             
8317 (v6)                  ALLOW       Anywhere (v6)             
8316 (v6)                  ALLOW       Anywhere (v6)   `

UFW status already set these ports to allow as well.

**Comment by JustinCheng0509** [comment]
After another round of double checking the config set the multiaddress to 127.0.0.1/tcp/8337, this is the error I get. 


panic: error getting token info: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: read tcp 127.0.0.1:52292->127.0.0.1:8337: use of closed network connection"

**Comment by eriksyuan** [comment]
i as

> After another round of double checking the config set the multiaddress to 127.0.0.1/tcp/8337, this is the error I get.
> 
> panic: error getting token info: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: read tcp 127.0.0.1:52292->127.0.0.1:8337: use of closed network connection"

I also encountered this problem. How did you solve it in the end
