### ISSUE TITLE
Unable to run Quilibrium using go run . : Panic: 404 Page Not Found

### ISSUE THREAD

**Issue by DevLuke91** [QuilibriumNetwork/ceremonyclient#7]
I'm encountering an issue while trying to run Quilibrium using the command go run . in the console. The program throws a panic error with the message "404 page not found." This error prevents me from running the application successfully.

**Comment by CassOnMars** [comment]
This was due to the conclusion of the first phase of the ceremony, launch is in progress. See more details here: https://warpcast.com/cassie/0x1da4a1
