### ISSUE TITLE
when run node error occurs

### ISSUE THREAD

**Issue by AceLuodan** [QuilibriumNetwork/ceremonyclient#73]
when i run command:GOEXPERIMENT=arenas go run ./...

error:
# runtime/cgo
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

i use go1.21.5 darwin/arm64.MAC M1

**Comment by tradersquareoff** [comment]
Wrong version of go. Consider using 1.20.14 instead

**Comment by CassOnMars** [comment]
This appears to be an xcode installation-specific issue, you need to make sure of two things:
1. that you have the correct version of go installed (1.20.x)
2. that you have a correctly specified developer path (via xcode-select)
