### ISSUE TITLE
Arena

### ISSUE THREAD

**Issue by Ayakuka** [QuilibriumNetwork/ceremonyclient#76]

**Comment by Ayakuka** [comment]
~/ceremonyclient/node# ./poor_mans_cd.sh
no processes running
process started with PID 4015 and child PID 
build source.quilibrium.com/quilibrium/monorepo/node: cannot load arena: malformed module path "arena": missing dot in first path element

what is the issue?

**Comment by CassOnMars** [comment]
seems that you may be running an old version of golang
