### ISSUE TITLE
fatal: unable to access 'https://github.com/QuilibriumNetwork/ceremonyclient/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by hkfish01** [QuilibriumNetwork/ceremonyclient#77]
When running the node's sh, it show a [1] 351210, then another command line start again with below message and then no response. 

in the log file, it has below error.

fatal: unable to access 'https://github.com/QuilibriumNetwork/ceremonyclient/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.

**Comment by CassOnMars** [comment]
seems there is a connectivity issue when the `git fetch` command in the script is run, this is likely an issue that can be improved in the poor_mans_cd.sh script, although this is not prioritized because this script is going to be shortly irrelevant
