### ISSUE TITLE
Instructions For Adding A Bootstrap Peer

### ISSUE THREAD

**Issue by CassOnMars** [QuilibriumNetwork/ceremonyclient#8]
In order to coordinate peering in a simple location, this issue will serve to track peer additions. After generating a peer id, please report back with the multiaddr format of your node, e.g.:

```/ip4/<ip addr>/udp/8336/quic/p2p/<peer id>```

Please remember that bootstrap peers must have static ips, and should remain online as much as possible – these nodes will be first contact peers which other nodes will connect to in order to discover the network graph, until we move into the phase where the DHT is no longer necessary.

**Comment by CassOnMars** [comment]
Adding a peer to the bootstrap list requires a commit in the form of the following:
https://github.com/QuilibriumNetwork/ceremonyclient/commit/d007a3d739eb156396573c62158d3c30499d4886

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/9 Added

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/10 Added

**Comment by CassOnMars** [comment]
As these peers are added, be sure to update your local node/.config/config.yml file to reflect the new peers:

```
...
p2p:
...
  bootstrapPeers: [
    "/dns/bootstrap.quilibrium.com/udp/8336/quic/p2p/QmUhm9iZVruSxyavjoPLCfuoRG94SGQEkfxEEoukEZmD5B",
    "/ip4/204.186.74.47/udp/8317/quic/p2p/Qmd233pLUDvcDW3ama27usfbG1HxKNh1V9dmWVW1SXp1pd",
    "/ip4/13.237.250.230/udp/8317/quic/p2p/QmazMeSUA9HPLuj53w56k6GUq3xVny3pHtosUZndejJeai",
    "/ip4/13.236.219.103/udp/8317/quic/p2p/QmcJqNsJLNfxkAxeJijfLppiNQERaeFuwsbg3BGScKqrfh"
  ]
  listenMultiaddr: /ip4/0.0.0.0/udp/8336/quic
...
```

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/11 added

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/12 added

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/13 added

**Comment by cincauhangus** [comment]
would a dynamic DNS work?

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/14 added

**Comment by CassOnMars** [comment]
> Do you accept Dynamic DNS?

For bootstrap peers, we need nodes to remain on static IPs, but nodes with dynamic IPs are free to connect to the network, even now, although for now we are only verifying the DHT peerlist is being properly maintained and the base network is functioning correctly.

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/15 added

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/16 added

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/17 added

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/18 added

**Comment by CassOnMars** [comment]
https://github.com/QuilibriumNetwork/ceremonyclient/pull/19 added

No further bootstrap peers will be added at this time. For the latest update regarding the launch for Dawn: https://warpcast.com/quilibrium/0xceaaa1
