### ISSUE TITLE
is there a way to fix this error its start after update

### ISSUE THREAD

**Issue by MyFreeSpace888** [QuilibriumNetwork/ceremonyclient#83]
###############                                  ###############
           #################&                                ##############%
              #########################&&&#############        ###############
                 ########################################%        ############
                     #######################################        ########
                          #############################                ##

                         Quilibrium Node - v1.3.0 – Dawn

panic: yaml: line 3: could not find expected ':'

goroutine 1 [running]:
main.main()
        /root/ceremonyclient/node/main.go:141 +0xb96
exit status 2

**Comment by Freekers** [comment]
Repull the repo and try again.
