### ISSUE TITLE
Node running for 3 days but balance at 0

### ISSUE THREAD

**Issue by jonathandune** [QuilibriumNetwork/ceremonyclient#87]
Hello,

I've been running a node for about 3 days, first 1.3.0 and now v1.4.0 – Sunset, but the QUIL balance stays at 0.
How can I tell whether the node has synced ?
Seems like I'm past peer discovery but I don't see any mentions of frames.

Logs :

                       Quilibrium Node - v1.4.0 – Sunset
 
Loading ceremony state and starting node...
{"level":"info","ts":1709315721.6114168,"caller":"node/main.go:244","msg":"generating difficulty metric"}
{"level":"info","ts":1709315744.309308,"caller":"node/main.go:266","msg":"generating entropy for commit/proof sizes"}
{"level":"info","ts":1709315744.3972023,"caller":"node/main.go:283","msg":"generating 16 degree commitment metric"}
{"level":"info","ts":1709315744.4691756,"caller":"node/main.go:292","msg":"generating 128 degree commitment metric"}
{"level":"info","ts":1709315745.0463583,"caller":"node/main.go:301","msg":"generating 1024 degree commitment metric"}
{"level":"info","ts":1709315749.89425,"caller":"node/main.go:310","msg":"generating 65536 degree commitment metric"}
{"level":"info","ts":1709316047.329166,"caller":"node/main.go:319","msg":"generating 16 degree proof metric"}
{"level":"info","ts":1709316047.4060285,"caller":"node/main.go:328","msg":"generating 128 degree proof metric"}

Any pointers ?

**Comment by jonathandune** [comment]
Node is now at that stage

{"level":"info","ts":1709327156.6841326,"caller":"ceremony/broadcast_messaging.go:328","msg":"clock frame was valid","address":"AIAAAAAAAAAEAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAPAVyCbkWVDUUSKVMpVFIXF9cwmk0gg+V4aidqSi9eMAUybnbBt6X7JfvdvQg+hk=","filter":"AIAAAAAAAAAEAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAPAVyCbkWVDUUSKVMpVFIXF9cwmk0gg+V4aidqSi9eMAUybnbBt6X7JfvdvQg+hk=","frame_number":1881}
{"level":"info","ts":1709327156.6848013,"caller":"ceremony/peer_messaging.go:457","msg":"processing frame","frame_number":1882,"aggregate_commits":1}
{"level":"info","ts":1709327156.684841,"caller":"ceremony/peer_messaging.go:473","msg":"found matching proof","frame_number":1882,"commit_index":0}
{"level":"info","ts":1709327156.7010934,"caller":"ceremony/broadcast_messaging.go:310","msg":"got clock frame","address":"AIAAAAAAAAAEAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAPAVyCbkWVDUUSKVMpVFIXF9cwmk0gg+V4aidqSi9eMAUybnbBt6X7JfvdvQg+hk=","filter":"AIAAAAAAAAAEAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAPAVyCbkWVDUUSKVMpVFIXF9cwmk0gg+V4aidqSi9eMAUybnbBt6X7JfvdvQg+hk=","frame_number":1882,"proof_count":1}

And it also seems to be processing frames from time to time

**Comment by Freekers** [comment]
Same issue here. Running since v1.2.15 but my balance is still 0. Not sure if that's intended behavior.

**Comment by CassOnMars** [comment]
Please check out the notes at https://paragraph.xyz/@quilibrium.com/mission-control for more info
