### ISSUE TITLE
Node error Report: Out of memory: Killed process 1837 (node) total-vm:47604924KB, anon-rss: 29873432KB, file-rss:0KB, UID:0 pgtables: 75060KB oom_score_adj:0

### ISSUE THREAD

**Issue by talentbuilder** [QuilibriumNetwork/ceremonyclient#89]
Tomorrow I followed this link's steps [https://drive.google.com/file/d/1atQ2Gb8vLzqxiS2cqRAp9ojFNDJup3TU/view](url) to install ceremony client and client is scuccessful running. Just now, I saw an error showed that client was killed and threw an error: 

Out of memory: Killed process 1837 (node) total-vm:47604924KB, anon-rss: 29873432KB, file-rss:0KB, UID:0 pgtables: 75060KB oom_score_adj:0

<img width="1167" alt="image" src="https://github.com/QuilibriumNetwork/ceremonyclient/assets/10881940/65f68153-d862-473d-9dd8-9bc44a1692ef">

I think maybe this problem is a memory leak issue or I made some mistakes when I installed the client? Please help and look into it, many thanks.

My node installation enviroments:
ubuntu 22.04 on virtual box 
client version:  latest
go version: 1.20.17

**Comment by foolstack-omg** [comment]
I have the same problem. There must be a memory leak on the v1.4.0 version of node. My server which has 36GB RAM ran out of memory after one hour.

**Comment by talentbuilder** [comment]
> I have the same problem. There must be a memory leak on the v1.4.0 version of node. My server which has 36GB RAM ran out of memory after one hour.

I found a solution on Q's telegram, you can change config.yml which under .config dir and append:

memoryLimits:
  enabled: true
  maxMemoryMB: 8192

This limit the maximun usage of RAM to 8 GB, you can set a value according to your server for a try, good luck to you bro.

**Comment by Freekers** [comment]
CassOnMars stated here that 16GB is the minimum for dawn and that going OoM is a bug indeed:
https://github.com/QuilibriumNetwork/ceremonyclient/pull/75#discussion_r1507054925

However, not sure if this still holds for 1.4.0 (Dusk). I am currently seeing stable memory usage at 8GB after 24 hours of running the node.

**Comment by talentbuilder** [comment]
> > I have the same problem. There must be a memory leak on the v1.4.0 version of node. My server which has 36GB RAM ran out of memory after one hour.
> 
> I found a solution on Q's telegram, you can change config.yml which under .config dir and append:
> 
> memoryLimits: enabled: true maxMemoryMB: 8192
> 
> This limit the maximun usage of RAM to 8 GB, you can set a value according to your server for a try, good luck to you bro.


> CassOnMars stated here that 16GB is the minimum for dawn and that going OoM is a bug indeed: [#75 (comment)](https://github.com/QuilibriumNetwork/ceremonyclient/pull/75#discussion_r1507054925)
> 
> However, not sure if this still holds for 1.4.0 (Dusk). I am currently seeing stable memory usage at 8GB after 24 hours of running the node.

I updated my client to 1.4.0 several hours ago and it seems stable for now. May I ask if you do any changes to  your config.yml? 

I also made a shell program to monitor the RAM usage of whole system, when it exceed 80% then I will restart the client.

**Comment by talentbuilder** [comment]
> CassOnMars stated here that 16GB is the minimum for dawn and that going OoM is a bug indeed: [#75 (comment)](https://github.com/QuilibriumNetwork/ceremonyclient/pull/75#discussion_r1507054925)
> 
> However, not sure if this still holds for 1.4.0 (Dusk). I am currently seeing stable memory usage at 8GB after 24 hours of running the node.

I updated my client to 1.4.0 several hours ago and it seems stable for now. May I ask if you do any changes to  your config.yml? 

I also made a shell program to monitor the RAM usage of whole system, when it exceed 80% then I will restart the client.

**Comment by foolstack-omg** [comment]
> CassOnMars stated here that 16GB is the minimum for dawn and that going OoM is a bug indeed: [#75 (comment)](https://github.com/QuilibriumNetwork/ceremonyclient/pull/75#discussion_r1507054925)
> 
> However, not sure if this still holds for 1.4.0 (Dusk). I am currently seeing stable memory usage at 8GB after 24 hours of running the node.

It seems that the problem is not solved. I was running with gRPC/REST Support. Go version 1.2.0. 16core 32G RAM.

**Comment by Freekers** [comment]
> > CassOnMars stated here that 16GB is the minimum for dawn and that going OoM is a bug indeed: [#75 (comment)](https://github.com/QuilibriumNetwork/ceremonyclient/pull/75#discussion_r1507054925)
> > However, not sure if this still holds for 1.4.0 (Dusk). I am currently seeing stable memory usage at 8GB after 24 hours of running the node.
> 
> I updated my client to 1.4.0 several hours ago and it seems stable for now. May I ask if you do any changes to your config.yml?
> 
> I also made a shell program to monitor the RAM usage of whole system, when it exceed 80% then I will restart the client.

I made no changes to my config. I am running it without gRPC/REST support, maybe that's the difference.

**Comment by talentbuilder** [comment]
> > > CassOnMars stated here that 16GB is the minimum for dawn and that going OoM is a bug indeed: [#75 (comment)](https://github.com/QuilibriumNetwork/ceremonyclient/pull/75#discussion_r1507054925)
> > > However, not sure if this still holds for 1.4.0 (Dusk). I am currently seeing stable memory usage at 8GB after 24 hours of running the node.
> > 
> > 
> > I updated my client to 1.4.0 several hours ago and it seems stable for now. May I ask if you do any changes to your config.yml?
> > I also made a shell program to monitor the RAM usage of whole system, when it exceed 80% then I will restart the client.
> 
> I made no changes to my config. I am running it without gRPC/REST support, maybe that's the difference.

I think what you said makes a lot of sense. When the client reported an OOM error, my configuration file had gRPC and REST support enabled. Later, I reverted the configuration file, and now the memory consumption is much more stable. I will continue to observe for a while to see if any errors are still reported.

**Comment by talentbuilder** [comment]
> > > CassOnMars stated here that 16GB is the minimum for dawn and that going OoM is a bug indeed: [#75 (comment)](https://github.com/QuilibriumNetwork/ceremonyclient/pull/75#discussion_r1507054925)
> > > However, not sure if this still holds for 1.4.0 (Dusk). I am currently seeing stable memory usage at 8GB after 24 hours of running the node.
> > 
> > 
> > I updated my client to 1.4.0 several hours ago and it seems stable for now. May I ask if you do any changes to your config.yml?
> > I also made a shell program to monitor the RAM usage of whole system, when it exceed 80% then I will restart the client.
> 
> I made no changes to my config. I am running it without gRPC/REST support, maybe that's the difference.

After changing the configuration, this issue still occurs. I am now a bit confused; perhaps it's best to wait for updates in the GitHub repository。

**Comment by Freekers** [comment]
> > > > CassOnMars stated here that 16GB is the minimum for dawn and that going OoM is a bug indeed: [#75 (comment)](https://github.com/QuilibriumNetwork/ceremonyclient/pull/75#discussion_r1507054925)
> > > > However, not sure if this still holds for 1.4.0 (Dusk). I am currently seeing stable memory usage at 8GB after 24 hours of running the node.
> > > 
> > > 
> > > I updated my client to 1.4.0 several hours ago and it seems stable for now. May I ask if you do any changes to your config.yml?
> > > I also made a shell program to monitor the RAM usage of whole system, when it exceed 80% then I will restart the client.
> > 
> > 
> > I made no changes to my config. I am running it without gRPC/REST support, maybe that's the difference.
> 
> After changing the configuration, this issue still occurs. I am now a bit confused; perhaps it's best to wait for updates in the GitHub repository.

I celebrated too early, my node has suddenly also started to run OoM again :(

**Comment by talentbuilder** [comment]
> > > > > CassOnMars stated here that 16GB is the minimum for dawn and that going OoM is a bug indeed: [#75 (comment)](https://github.com/QuilibriumNetwork/ceremonyclient/pull/75#discussion_r1507054925)
> > > > > However, not sure if this still holds for 1.4.0 (Dusk). I am currently seeing stable memory usage at 8GB after 24 hours of running the node.
> > > > 
> > > > 
> > > > I updated my client to 1.4.0 several hours ago and it seems stable for now. May I ask if you do any changes to your config.yml?
> > > > I also made a shell program to monitor the RAM usage of whole system, when it exceed 80% then I will restart the client.
> > > 
> > > 
> > > I made no changes to my config. I am running it without gRPC/REST support, maybe that's the difference.
> > 
> > 
> > After changing the configuration, this issue still occurs. I am now a bit confused; perhaps it's best to wait for updates in the GitHub repository.
> 
> I celebrated too early, my node has suddenly also started to run OoM again :(

Let's keep an eye on the developments on Telegram and GitHub, hoping for a quick resolution to the issue. If possible, it would also be great to have the option to configure the maximum CPU cores used. Haha

**Comment by CassOnMars** [comment]
1.4.1 should have eliminated the last pathological GC issue, however you may find OOM killer events even still. If so, try switching your listenMultiaddr to use TCP instead of UDP/QUIC
