### ISSUE TITLE
I encountered this bug. process exit.

### ISSUE THREAD

**Issue by foolstack-omg** [QuilibriumNetwork/ceremonyclient#90]
{"level":"info","ts":1709319673.604675,"caller":"p2p/blossomsub.go:331","msg":"error while connecting to dht peer","error":"failed to dial: context deadline exceeded"}
signal: killed

**Comment by CassOnMars** [comment]
v1.4.1 has an important update to resolve the last identified pathological GC issue, however if you still experience this after the update, you may want to switch from QUIC to TCP
